// Code generated by "stringer -type=DaemonEvent"; DO NOT EDIT.

package common

import "strconv"

const _DaemonEvent_name = "InitializationCompleteCommandUpdateCodeInfoCommandUpdateRuntimeInfoCommandStartCommandKillCommandUploadCodeSuccessfullyStartedCodeNotStartedFailedToKillCodeKilledCodeResultUploadingErrorResultUploadingFinishedCodeFinishesOkCodeFinishesError"

var _DaemonEvent_index = [...]uint8{0, 22, 43, 67, 79, 90, 103, 126, 140, 156, 166, 186, 209, 223, 240}

func (i DaemonEvent) String() string {
	if i < 0 || i >= DaemonEvent(len(_DaemonEvent_index)-1) {
		return "DaemonEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DaemonEvent_name[_DaemonEvent_index[i]:_DaemonEvent_index[i+1]]
}
