// Code generated by "stringer -type=DaemonState"; DO NOT EDIT.

package common

import "strconv"

const _DaemonState_name = "InitializingPreparationUpdateInProgressCodeRunningCodeBeingKilledCodeFailedToKillCodeKilledCodeStoppedCodeErrorResultUploadingStateResultUploadingErrorStateResultUploadingCompleteState"

var _DaemonState_index = [...]uint8{0, 12, 23, 39, 50, 65, 81, 91, 102, 111, 131, 156, 184}

func (i DaemonState) String() string {
	if i < 0 || i >= DaemonState(len(_DaemonState_index)-1) {
		return "DaemonState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DaemonState_name[_DaemonState_index[i]:_DaemonState_index[i+1]]
}
