// Code generated by "stringer -type=DaemonEvent"; DO NOT EDIT.

package common

import "strconv"

const _DaemonEvent_name = "InitializationCompleteReceiveCodeInfoReceiveRuntimeInfoReadyToStartStartCommandReceivedKillCommandReceivedUploadCommandReceivedCodeSuccessfullyStartedCodeNotStartedFailedToKillCodeKilledCodeResultUploadingErrorResultUploadingFinishedCodeFinishesOkCodeFinishesError"

var _DaemonEvent_index = [...]uint16{0, 22, 37, 55, 67, 87, 106, 127, 150, 164, 180, 190, 210, 233, 247, 264}

func (i DaemonEvent) String() string {
	if i < 0 || i >= DaemonEvent(len(_DaemonEvent_index)-1) {
		return "DaemonEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DaemonEvent_name[_DaemonEvent_index[i]:_DaemonEvent_index[i+1]]
}
