// Code generated by "stringer -type=Event"; DO NOT EDIT.

package common

import "strconv"

const _Event_name = "InitializationCompleteReceiveCodeInfoReceiveRuntimeInfoReadyToStartStartCommandReceivedKillCommandReceivedUploadCommandReceivedCodeSuccessfullyStartedCodeNotStartedFailedToKillCodeKilledCodeResultUploadingErrorResultUploadingFinishedCodeFinishesOkCodeFinishesError"

var _Event_index = [...]uint16{0, 22, 37, 55, 67, 87, 106, 127, 150, 164, 180, 190, 210, 233, 247, 264}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
