// Code generated by "stringer -type=Event"; DO NOT EDIT.

package common

import "strconv"

const _Event_name = "InitializationCompleteEventStartCommandReceivedKillCommandReceivedDaemonFailedToKillCodeDaemonKilledCodeUploadCommandReceivedUpdateReceivedUpdateFinishedResultUploadingErrorEventResultUploadingFinishedEventCodeFinishesOkCodeFinishesError"

var _Event_index = [...]uint8{0, 27, 47, 66, 88, 104, 125, 139, 153, 178, 206, 220, 237}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
